esp32:
  board: nodemcu-32s

esphome:
  name: display3
  includes:
    - utils.h
  on_boot:
    priority: 200
    then:
      - light.turn_on:
          id: display_brightness
          brightness: 70%

wifi:
  ssid: "Shayan"
  password: "bazingaa"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espruby Fallback Hotspot"
    password: "epsilontango"

captive_portal:
json:

# Enable logging
logger:
api:
  password: "epsilontango"

ota:
  - platform: esphome
    password: "epsilontango"

sun:
  latitude: 12.888838
  longitude: 77.610265

time:
  - platform: sntp
    id: sntp_time

light:
  - platform: monochromatic
    name: "Display Brightness"
    output: display_led_out
    id: display_brightness

output:
  - platform: ledc
    id: display_led_out
    pin: GPIO19

font:
  - file: "fonts/SF-Pro-Display-Semibold.ttf"
    id: sf_pro_24
    size: 24
  - file: "fonts/SF-Pro-Display-Medium.ttf"
    id: sf_pro_96
    size: 96
    glyphs: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "A", "M", "P", " ", ":"]
  # MDI v7.4.47
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: mdi
    size: 26
    glyphs: ["\U000F058C", "\U000F0599", "\U000F140B", "\U000F0594", "\U000F0E02", "\U000F0E03", "\U000F0717", "\U000F058D"]
    # drop, sun, current_consumption, night,thermometer-chevron-down, thermometer-chevron-up, snowflake, water-off

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

display:
  - platform: ili9xxx
    model: ili9341
    reset_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO15
    rotation: 180
    dimensions:
      height: 320
      width: 240
    update_interval: 5s
    show_test_card: true
    invert_colors: true
    color_palette: 8BIT
    # - platform: st7735
    #   model: "INITR_18BLACKTAB"
    #   reset_pin: GPIO4
    #   cs_pin: GPIO1 #D1
    #   dc_pin: GPIO2 #D2
    #   rotation: 0
    #   device_width: 128
    #   device_height: 160
    #   col_start: 0
    #   row_start: 0
    #   eight_bit_color: true
    #   update_interval: 5s
    id: my_display
    lambda: |-
      const unsigned short int padding = 6, HEIGHT = 240, WIDTH = 320, 
            fontHeight = 24, iconWidth = fontHeight + padding,
            DEFAULT_MIN_TEMP = 100;
      const unsigned short int midX = WIDTH/2, 
            bottomMax = HEIGHT - (padding*2 + fontHeight), 
            col2Start = midX,  
            row1FontY = midX;

      it.rectangle(0,  0, it.get_width(), it.get_height(), id(my_red));

      // date
      it.strftime(padding, padding, id(sf_pro_24), "%a, %b %d", id(sntp_time).now());
      // time
      char time_str[6];
      struct tm tm_now = id(sntp_time).now().to_c_tm();
      strftime(time_str, sizeof(time_str), "%I:%M", &tm_now);
      removeLeadingZeros(time_str);
      it.printf(midX, fontHeight + padding, id(sf_pro_96), TextAlign::TOP_CENTER,  "%s", time_str);


